Fix gdb-add-symbol-file (2 text sections) - libdmtcp.so can have two 'r-x' sections since DMTCP-2.1. It's not clear why.

diff --git a/trunk/util/gdb-add-symbol-file b/trunk/util/gdb-add-symbol-file
--- a/trunk/util/gdb-add-symbol-file
+++ b/trunk/util/gdb-add-symbol-file
@@ -16,29 +16,27 @@ test -z "$2" && echo '    ' ... and paste the output of that command into gdb:
 test -z "$2" && echo Hence: '(gdb) add-symbol-file ...'
 test -z "$2" && exit
 
-# processPID=`pgrep -n $1`
-#processPID=$1
-#if ! test -e /proc/$processPID; then
-#  echo Process $processPID does not exist.  Please use existing proces.
-#  exit 1
-#fi
-#if test -z "`cat /proc/$processPID/maps | grep $2`"; then
-#  echo "**** Library $2 not found. "\
-#       "Do:  cat /proc/$processPID/maps  to see all libs."
-#  exit 1
-#fi
-#
-#lib=`cat /proc/$processPID/maps | grep $2 | head -1 | \
-#	sed -e 's%[^/]*\(/.*\)%\1%'`
-#
-#segAddr=`cat /proc/$processPID/maps | grep $lib | grep r-xp | \
-#	sed -e 's%^\([0-9a-f]*\).*%0x\1%'`
-#segDataAddr=`cat /proc/$processPID/maps | grep $lib | grep rw-p | \
-#	sed -e 's%^\([0-9a-f]*\).*%0x\1%'`
-#
-lib=$1
-echo $lib
-segAddr=$2
+processPID=`pgrep -n $1`
+processPID=$1
+if ! test -e /proc/$processPID; then
+  echo Process $processPID does not exist.  Please use existing proces.
+  exit 1
+fi
+if test -z "`cat /proc/$processPID/maps | grep $2`"; then
+  echo "**** Library $2 not found. "\
+       "Do:  cat /proc/$processPID/maps  to see all libs."
+  exit 1
+fi
+
+lib=`cat /proc/$processPID/maps | grep $2 | head -1 | \
+	sed -e 's%[^/]*\(/.*\)%\1%'`
+
+# libdmtcp.so can now have two r-x sections.  Why?
+segAddr=`cat /proc/$processPID/maps | grep $lib | head -1 | grep r-xp | \
+	sed -e 's%^\([0-9a-f]*\).*%0x\1%'`
+segDataAddr=`cat /proc/$processPID/maps | grep $lib | grep rw-p | \
+	sed -e 's%^\([0-9a-f]*\).*%0x\1%'`
+
 textOffset=`readelf -S $lib | grep '\.text ' | \
 	sed -e 's%^.*text[^0-9a-f]*[0-9a-f]* \([0-9a-f]*\).*%0x\1%'`
 dataOffset=`readelf -S $lib | grep '\.data ' | \
